services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_TCP_PORT: ${MYSQL_TCP_PORT}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [
        "CMD",
        "mysqladmin",
        "ping",
        "-h", "${MYSQL_HOST}",
        "-P", "${MYSQL_TCP_PORT}",
        "-u", "${MYSQL_USER}",
        "-p${MYSQL_PASSWORD}"
      ]
      interval: 5s
      timeout: 5s
      retries: 5
 
  

  app:
    build: .
    volumes: 
      - uploads:${UPLOAD_DIR}
    ports:
      - "${PORT}:3000"
    
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
  uploads:
    